name: toronto
favicon: null
layout_spectrum: 0.5802231598645449
typography_spectrum: 0.17951228516176343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1759162680245936
  lightness: 0.5647105791140348
  saturation: 0.49543402064591646
  rhythmicContrast: 0.2723551751114428
purpose: []
